local Config = require("config")

return Config:init()
		:append(require("config.appearance"))
		:append(require("config.fonts"))
		:append(require("colors.custom"))
		:append(require("config.general")).options

-- local config = {
-- 	color_scheme = "Everforest Dark (Gogh)",
--
-- 	allow_square_glyphs_to_overflow_width = "Never",
-- 	force_reverse_video_cursor = true,
-- 	-- use_ime = true,
-- 	-- adjust_window_size_when_changing_font_size = true,
--
-- 	font = wezterm.font_with_fallback({
-- 		-- { family = "Zed Mono", assume_emoji_presentation = false },
-- 		{ family = "Hack Nerd Font Mono", assume_emoji_presentation = true },
-- 		-- { family = "Symbols Nerd Font Mono" }
-- 	}),
-- 	font_size = 20,
--
-- 	window_close_confirmation = "NeverPrompt",
-- 	window_decorations = "RESIZE",
-- 	cell_width = 1.0,
-- 	line_height = 1.1,
-- 	window_padding = {
-- 		left = 0,
-- 		right = 0,
-- 		top = 0,
-- 		bottom = 0,
-- 	},
-- 	initial_rows = 50,
-- 	initial_cols = 100,
--
-- 	show_tabs_in_tab_bar = true,
-- 	-- hide_tab_bar_if_only_one_tab = true,
-- 	use_fancy_tab_bar = true,
-- 	tab_bar_at_bottom = true,
-- 	show_new_tab_button_in_tab_bar = false,
--
-- 	colors = {
-- 		tab_bar = {
-- 			background = "#ffffff",
--
-- 			active_tab = {
-- 				bg_color = "#83c092",
-- 				fg_color = "#384b55",
-- 				intensity = "Normal",
-- 				underline = "None",
-- 				italic = false,
-- 				strikethrough = false,
-- 			},
--
-- 			inactive_tab = {
-- 				bg_color = "#495156",
-- 				fg_color = "#c6c8d1",
-- 				intensity = "Normal",
-- 				underline = "None",
-- 				italic = false,
-- 				strikethrough = false,
-- 			},
--
-- 			inactive_tab_hover = {
-- 				bg_color = "#3c3836",
-- 				fg_color = "#c6c8d1",
-- 				intensity = "Normal",
-- 				underline = "None",
-- 				italic = true,
-- 				strikethrough = false,
-- 			},
--
-- 			new_tab = {
-- 				bg_color = "#1b1f2f",
-- 				fg_color = "#c6c8d1",
-- 				italic = false,
-- 			},
--
-- 			new_tab_hover = {
-- 				bg_color = "#444b71",
-- 				fg_color = "#c6c8d1",
-- 				italic = false,
-- 			},
-- 		},
-- 	},
-- 	window_frame = {
-- 		inactive_titlebar_bg = "#353535",
-- 		active_titlebar_bg = "#1d2021",
-- 		inactive_titlebar_fg = "#cccccc",
-- 		active_titlebar_fg = "#ffffff",
-- 		inactive_titlebar_border_bottom = "#2b2042",
-- 		active_titlebar_border_bottom = "#2b2042",
-- 		button_fg = "#cccccc",
-- 		button_bg = "#2b2042",
-- 		button_hover_fg = "#ffffff",
-- 		button_hover_bg = "#3b3052",
-- 	},
-- }

-- return config
